### ISSUE TITLE
Project Home dropdowns not stacking

### ISSUE THREAD

**Issue by jpcjr** [jpcjr/corvid#85] opened 2015-12-02 21:12 UTC
Multiple entries in the project home dropdowns don't stack properly. I recall them doing so earlier though. I see the following with 2 entries (for Category, Proj. Plugin, and Page Plugin):

![Mis-stacked Buttons]
(https://cloud.githubusercontent.com/assets/2373100/11544241/e17e07d2-990e-11e5-83a0-551400a2f42d.png)

half-corrects with 3, though:

![screenshot from 2015-12-02 16 10 24](https://cloud.githubusercontent.com/assets/2373100/11544307/366aadd6-990f-11e5-8dc2-7adb8c8a418e.png)

Can other people reproduce this? @dealie16 any thoughts?

**Comment by brenns10** [comment] 2015-12-02 21:25
I reproduced this looking at categories in TSwizzle.  Not sure why I didn't see it before.  I was able to fix it by adding `<br>` tags in between each `<li>`.  I think it's due to the floating `<div>` elements being within an inline `<li>` element.  I get the feeling that you're not supposed to float things within an inline element...

**Comment by brenns10** [comment] 2015-12-03 16:44
Fixed by #89, but apparently not closed.

**Closed by brenns10** 2015-12-03 16:44 UTC
Labels: bug
